# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git config --global user.email "$(EMAIL)"
    git config --global user.name "$(USERNAME)"
  displayName: 'Set git configs.'

- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: '$(Build.Repository.Uri)'
    destinationGitRepositoryUri: 'https://github.com/kamasylvia/live2d_api.git'
    destinationGitRepositoryPersonalAccessToken: '$(PERSONAL_ACCESS_TOKEN)'
